version: '3'
services: # you can build by command docker-compose up -d --build (it will call any compose that I extend)
  api:
    extends:
      file: docker-compose-springboot.yml
      service: backend
  # don't forget db it has to use accessing database (jdbc:mysql://db:3306/books)
  db:
    extends:
      file: docker-compose-database.yml
      service: database

# if you work with extends service you have to set volumes,networks again
# setting volume and network again when Service that extend sets it
volumes: # for storing value on container (can call service in backend part)
  information-database: # define volume name
    driver: local # use only current pc1

networks: # It's Importance. Create a docker network to communicate Spring boot application and MySQL database
  springboot-network:  # Here springboot-mysql-net is the network name.