version: '3'
services:
  backend:
    container_name: springboot
    build:
      # way to accessing Dockerfile on folder
      context: . # relative to docker-compose command running directory (.) means this folder
      dockerfile: dockers/springboot/Dockerfile # specify path to Dockerfile it starts on current folder application
    image: springboot
    ports:
      - '${SPRINGBOOT_EXPOSED_PORT}:8080'
      # depends_on: dependency order, mysqldb is started before backend ?
      # - database
    env_file:
      - .env
    links: # to link containers over a network. When we link containers, Docker creates environment variables and adds containers to the known hosts list
      - db # call service db name on docker-compose main (That I extend) now I can't use service name database
    environment: # environmental variables for instead  Spring Boot application.prop file
      # - spring.datasource.url=jdbc:mysql://db:3306/$SQLD_DATABASE?allowPublicKeyRetrieval=true # OR
      - spring.datasource.url=jdbc:mysql://db:3306/$SQLD_DATABASE
      - spring.datasource.username=$SQLD_USERNAME
      - spring.datasource.password=$SQLD_PASSWORD
    networks:
      - springboot-network